goagent/3.1.48/local/web_control.py
goagent/3.1.48/web_ui/deploy.html

Reverts XX-net/XX-Net#186
not work, revert first.

Revert "add [Cancel] button to deploy page"

---

goagent/3.1.48/server/uploader.py

Reverts XX-net/XX-Net#176
https://groups.google.com/d/msgid/xx-net/2d8b7292-a38c-4938-9c2e-3e512aec0be2%40googlegroups.com?utm_medium=email&utm_source=footer
not work on mac and windows.
need more check, revert first.

Revert "Update uploader.py"

---

goagent/3.1.49/web_ui/config.html
goagent/3.1.49/web_ui/deploy.html
launcher/1.4.0/web_ui/css/style.css

Remove <font> tag as it's deprecated in HTML 5.
Fix bug: Change the link of manually config GoAgent from hhttps to https.

Refine HTML and JavaScript of New Web UI.

---

goagent/3.1.49/web_ui/deploy.html

对Pull Request #219的改进.
1. 去掉HTML的空行
2. 统一JavaScript中的变量风格, 使用驼峰式命名法.(本人有非常严重的强迫症, 请谅解)
3. Bug Fix: 在(新文件的)第246行, 将`;`改为`,`. 否则`rc4Password`会变成一个全局变量. 虽然对功能无影响, 但是的确是不合乎语义的.
BTW, 在`launcher/1.4.0/web_ui/config.html`中添加的PHP模式开关是什么意思? 
那个开关不是在PHP的config中已经有了吗?

Refine the HTML and JS in goagent config page.

---

goagent/3.1.49/web_ui/config.html
goagent/3.1.49/web_ui/deploy.html
goagent/3.1.49/web_ui/status.html

很多人看着Block stat一直在倒计时，不明白到底是什么意思，因此我认为在Wiki上加以说明可能好一些，同时可以在Wiki上引导用户提交bad_ip.txt。
以及在页面中有不少地方中英文标点混用，主要体现在逗号是中文状态，句尾的句号却是英文状态，这次提交中统一了一下。

增加Block stat的说明 以及统一标点的使用

---

goagent/3.1.49/web_ui/importip.html
launcher/1.4.0/web_ui/css/style.css

消失了好几天之后回归啦~!
1. 主要是修改了导入IP页面的布局
2. 拆分了JS代码, 一个函数也太长不容易维护.
3. PS: `conversionFormat(sf, tf, ss)`这三个参数到底是几个意思呀?

Refine the HTML and JS in import IP page.

---

goagent/3.1.49/local/google_ip.py

修复逻辑，此前并不能真正的移除和将结果保存到good_ip文件。

fixes real remove

---

goagent/3.1.49/web_ui/logging.html

br未见必要性，有p标签应该会自动换行吧。
改用css更加标准，性能应该也会稍好一点。

Logging class

---

goagent/3.1.49/local/appids_manager.py

看了看现有的代码，在所有APPID都用光流量的时候，会重置所有APPID为可用的，这个过程中却没有清空不可用APPID的列表，这个时候应该会在WebUI上出现一个APPID即在可用列表又在无流量列表的情况。
以上没经过实际测试，仅作为我的猜测。

APPID显示异常的修复

---

goagent/3.1.49/local/web_control.py

https://groups.google.com/forum/#!msg/xx-net/vPfKiG3GJDk/d7Tuw_PXkE8J

save ip_list immediately after import

---

goagent/3.1.49/web_ui/ipconfig.html
goagent/3.1.49/web_ui/scan_ip.html
goagent/3.1.49/web_ui/status.html

主要修正了GoAgent的Status页面中第二个`table`的不符合HTML标准的地方.
将第2-4行的内容移动至`tbody`标签中.
其他的文件随手删了几个无意义的空行: HTML中`<div class="row-fluid">`之间.
随手统一了一下JS中的函数命名规则: 采用驼峰式命名法.

Fix some code which doesn't meet the HTML standard.

---

goagent/3.1.49/web_ui/status.html

add `var`, fix `for in` fail in IE

---

goagent/3.1.49/local/google_ip.py
goagent/3.1.49/local/web_control.py

rewrite ip_handshake_100 to ip_handshake_th

---

goagent/3.1.49/web_ui/scan_ip.html
goagent/3.1.49/web_ui/status.html

本次PR改进如下:
1. 在GoAgent模块的状态页(`status.html`), 将每个section的标题用`<h4>`突出显示, 已取代先前的`<div>`.
2. 在GoAgent模块的扫描IP页(`scan_ip.html`), 修正一处Bug (第115行, JS中的Selector中漏了一个`#`)导致页面中的自动扫描开关样式显示有一点诡异.
3. 在GoAgent模块的扫描IP页(`scan_ip.html`), 改进了一下响应式的排版布局.
4. 在GoAgent模块的扫描IP页(`scan_ip.html`), 将每一段逻辑无关的JS用`<script>`标签分离.

Fix some bugs and Format the Code

---

goagent/3.1.49/local/openssl_wrap.py

fix bug to support TLSv1.2

---

goagent/3.1.49/web_ui/scan_ip.html

修复 Pull Request #580 引入的Bug.
我错了 T^T

Fix a bug that the switch of status.html page not working.

---

.gitignore
gae_proxy/local/cert_util.py
php_proxy/local/cert_util.py

Android CA证书 v3 extension basic constraints

---

gae_proxy/local/web_control.py

显示成这样应该没有什么问题了吧
Property  | Value
------------ | --------------
Sys Platform | AMD64, Windows-7-6.1.7601-SP1

fix Issue 996

---

launcher/web_control.py

原来的日志输出好像有点问题 `finished confirm_xxnet_exit`打不出来，小调整一下

minor fix for logging output of "confirm xxnet exit"

---

launcher/config.py
launcher/gtk_tray.py
launcher/mac_tray.py
launcher/setup.py
launcher/start.py
launcher/web_control.py
launcher/web_ui/config.html
launcher/win_tray.py

在https://github.com/XX-net/XX-Net/pull/1076 基础上提交的，增加了在设置页面的“允许远程连接Web控制端”开关。
X大过目没问题就合这个PR吧，我把原来的PR 1076关了

fix #1068 && add "allow remote webcon" in setting page

---

gae_proxy/local/connect_control.py
gae_proxy/local/proxy.py
gae_proxy/start.py
launcher/module_init.py
launcher/web_ui/config.html

检测keep_running
https://github.com/XX-net/XX-Net/blob/master/gae_proxy/local/proxy.py#L262-L263
但不知道什么地方，会把keep_running弄成False。
现象就是：设置页面，重启GAEProxy的时候，服务刚起来，就因为keep_running被False了，导致服务马上停止。
**我还没找到是什么地方设置的这个False**，所以先在gae_proxy/start.py的main中，提前设置keep_running为True
请X大看看，是什么地方把这个keep_running搞成了False，谢谢。

[WIP]fix issue 1079

---

gae_proxy/web_ui/status.html

自动生成诊断信息，提交到issue。也可以仅仅输出诊断信息。
我在issue区提交了一个自动创建的模板范例。
感觉还有很大改善余地，求指点。

状态信息页：自动创建issue模板，或仅生成诊断信息

---

gae_proxy/server/uploader.bat
gae_proxy/server/uploader.py

顺便想问下- -
https://github.com/XX-net/XX-Net/issues/1438

gae部分server的两个小修正

---

README.md

给readme加几个链接，添加“更新历史”wiki页面链接

---

gae_proxy/web_ui/status.html

修复了一个逻辑错误.
在非专家模式, 我没使用公共账号, 却被识别为使用公共账号.

Fix some bugs of detecting public AppID.

---

launcher/web_ui/css/style.css

Improve UI for Mac OS.

---

README.md

As the title implied, a new section is added to list the UI languages XX-Net now supports. Please keep my version as many trivial errors were corrected in the text.

Add a supported language list in README.md

---

gae_proxy/local/config.py

fix https://github.com/XX-net/XX-Net/issues/1653#issuecomment-166172298

strip whitespace around appid

---

gae_proxy/web_ui/status.html
launcher/web_control.py
launcher/web_ui/css/style.css

Update webui status info

---

gae_proxy/web_ui/status.html

fix refresh page display blank

---

README.md
gae_proxy/web_ui/config.html

主要改进2个问题
1. GAE的配置页面, 最下面那行提示"Advanced tricks:: By the configuration file" 在英文状态下会换行, 原因是所在 div 宽度不够
2. README 中诡异的翻译: rebirth 感觉太 Chinglish 了吧.

Improvement

---

launcher/mac_tray.py

MacBook Air和MacBook Pro with Retina Display仅有Thunderbolt转接的以太网卡，名为Thunderbolt Ethernet。

Mac状态栏图标：添加自动代理选项和Thunderbolt以太网卡的支持

---

gae_proxy/local/google_ip.py
launcher/web_ui/css/style.css

1. 修复 jQuery 问题当slideDown或Up的时候内容会抖动
2. 调整最大扫描线程数为0时无效

fix shaking when slideDown or slideUp and cant adjust scan thread to 0

---

gae_proxy/local/google_ip.py

iplist_need_save 修改为布尔型

---

python27/1.0/lib/noarch/simple_http_server.py

Fix bug #1727

---

launcher/update.py

注释无意义代码，删除无用变量

---

launcher/win_tray.py
python27/1.0/lib/win32/win32_proxy_manager.py

修复拨号上网代理设置失败问题

---

README.md

The Persian (IR) home page is ready. It was suggested to keep the English along with  the Persian for people to understand better.

Created and linked the Persian (IR) page

---

launcher/web_ui/css/style.css
x_tunnel/lang/zh_CN/LC_MESSAGES/messages.po
x_tunnel/local/web_control.py
x_tunnel/web_ui/config.html

发现 @YeahWu 已经提交了2个PR. 估计这个PR会有冲突.
本PR主要改进了翻译, 同时页改进了在"套餐"页面中单击订购后的用户体验.
同时还有一个Bug:
在 PR #2097 中提到的, 当余额不足时, 单击购买套餐. 会退出登录.

Polish JS code & Translation

---

.gitignore
launcher/mac_tray.py

刚才那个PR有一点Bug.
因为之前那个作者在启用新的代理时没有禁用旧的代理.
就比如说, 我启用了PAC代理, 正要开启全局代理.
这时候PAC代理不会被关闭. 然后菜单的显示就会Bug.

Fix bugs of Pull request #2121.

---

launcher/lang/de_DE/LC_MESSAGES/messages.po
launcher/lang/en_US/LC_MESSAGES/messages.po
launcher/lang/es_VE/LC_MESSAGES/messages.po
launcher/lang/fa_IR/LC_MESSAGES/messages.po
launcher/lang/ja_JP/LC_MESSAGES/messages.po
launcher/lang/zh_CN/LC_MESSAGES/messages.po
launcher/web_control.py
launcher/web_ui/config.html
launcher/web_ui/css/style.css
launcher/web_ui/index.html
php_proxy/babel.config
php_proxy/lang/zh_CN/LC_MESSAGES/messages.po
php_proxy/pybabel_update.sh
php_proxy/web_ui/config.html
php_proxy/web_ui/logging.html
php_proxy/web_ui/menu.yaml

该PR主要改进如下:
1. 完成了PHP代理模块的国际化和中文本地化 (虽然Nobody cares)
2. 改进了系统配置页面的一处翻译 (`Restarting XX-Net Needed` -> `Restarting XX-Net Required`)
3. 修复了CSS的一处问题 (select等控件focus时边框的颜色与页面配色不符.)

Complete i18n for PHP proxy.

---

gae_proxy/lang/fa_IR/LC_MESSAGES/messages.po
gae_proxy/lang/zh_CN/LC_MESSAGES/messages.po
gae_proxy/web_ui/status.html

1. Add download ‘ca.cert' link
2. Translate it by google

Add download ca.cert link in status page

---

launcher/simple_i18n.py
launcher/web_control.py

虽然修复了Issue #2250 的问题, 但感觉不是作者的本意.
但又感觉没有更好的Fix的方法.

Fix a bug: Unknown error in config page.

---

gae_proxy/local/cert_util.py
gae_proxy/local/check_local_network.py
gae_proxy/local/google_ip.py
gae_proxy/local/proxy.py
gae_proxy/local/test_appid.py
launcher/autorun.py
launcher/config.py
launcher/create_shortcut.js
launcher/setup.py
launcher/setup_win_python.py
launcher/update_from_github.py
lib/noarch/socks.py
start.vbs

1. temporary disable x_tunnel
2. fix start.vbs
3. fix test appid
4. change python path in some files

Fix start.vbs , test-appid , disable x-tunnel and change python path in some files

---

gae_proxy/local/proxy_handler.py

Fix could not get right content (eg: img  file) from webcontrol through
proxy

Fix content error in forward_local

---

gae_proxy/local/web_control.py

#2414. Tested works in Firefox.

Use appropriate header for install as CA

---

launcher/mac_tray.py

在设置代理时只会动当前连接的设置，退出时会清空所有代理设置。切换网络服务时会自动刷新。
修复#2490

Mac状态栏：检测当前使用的网络服务

---

launcher/win_tray.py
python27/1.0/lib/win32/systray/traybar.py

汉化该菜单，保持统一。不知道这个lib来自哪里，但以前也改过，所以继续改吧。
新提交的转移到Python3分支如何处理，会定期或最终一并处理吗。

i18n for 'Quit' in win_tray

---

launcher/mac_tray.py

将Helper权限降为755以防止被低权限程序修改
将os.system替换为subprocess.call

Mac Tray: Security Improvements

---

launcher/mac_tray.py

AppKit包含很多符号，`from AppKit import *`会耗费大量时间
在我电脑（mid-2012 MacBook Pro）上启动时间从4.25s降为0.21s

Mac：大幅提升启动速度

---

launcher/mac_tray.py

只有root helper正常安装时才会加载配置，以避免改变网络配置时多次弹出密码输入框

Mac：从配置文件读取设置

---

gae_proxy/lang/zh_CN/LC_MESSAGES/messages.po

这句话我已经忍了很久了！
好吧 我承认这个Commit有点水～ 不符合我的风格。

Polish translation.

---

start.sh

Improve #2761 when launch XX-Net without Terminal

隐藏在mac上启动时的终端

---

start.vbs

Fix misspell in start.vbs.

---

code/default/gae_proxy/web_ui/scan_setting.html

Fix #1960
忍了好久还是没人修- -
所以我自己来了个- -
谁有空改改 python 部分的代码把这三个请求合并成一个吧- -
=============
刚刚发现这个 Pull 的 ID 是 #2960 - -

统一扫描设置的提交按钮

---

code/default/gae_proxy/local/web_control.py
code/default/gae_proxy/web_ui/scan_setting.html

合并**页面扫描**设置请求。减少3个接口请求为1个接口，具体修改web_console模块req_scan_ip_handler:
1. 删除 **set_auto_adjust_scan_ip_thread_num**接口
2. 删除 **set_scan_thread_num** 接口
3. 删除 **set_range**接口
4. 增加 **update**接口
5. 修改前端页面请求
@Cat7373

change 'scan_setting' requests to 'scan_ip?cmd=update' request

---

README.md
code/default/launcher/post_update.py

1. Check folder exists before delete
2. Add update description in README

Check folder exists before delete

---

code/default/gae_proxy/local/openssl_wrap.py

Refer to https://github.com/XX-net/XX-Net/issues/3120#issuecomment-215940542

Fix the gvs's ciphers

---

start

Add installation script for ArchLinux.

---

start

装了Fedora 23发现, Fedora用的不是`yum`, 所以改了一下脚本.

Fix installation script for Fedora.

---

.github/ISSUE_TEMPLATE.md

对比↓
以前：https://github.com/XX-net/XX-Net/issues/new
现在：https://github.com/Cat7373/XX-Net/issues/new

修改 Issue 模板

---

code/default/launcher/post_update.py

从git历史中整理出了黑名单，请帮忙看看是否还有遗漏
解决#3237

post_update中删除改黑名单制

---

code/default/gae_proxy/server/uploader.bat

这样可以保证所有参数都被传输到 py 脚本里。
另外我这里部署也有问题(https://github.com/XX-net/XX-Net/issues/3398) - -
根本就没弹出授权网页来。
*****\XX-Net\code\default\gae_proxy\server>uploader.bat xxnet-1 -password 123123 -debug -xxx
*****\XX-Net\code\default\gae_proxy\server>..\..\python27\1.0\python.exe uploader.py xxnet-1 -password 123123 -debug -xxx
2016-05-16 11:39:57,901 - root - INFO - use rc4_password: 123123
2016-05-16 11:39:57,901 - root - INFO - enable debug logging
2016-05-16 11:39:57,901 - root - INFO - unknow argv: -xxx
2016-05-16 11:39:57,901 - root - INFO - set proxy to http://127.0.0.1:8087
2016-05-16 11:39:57,901 - root - INFO - ============  Begin upload  ============
2016-05-16 11:39:57,901 - root - INFO - appid:xxnet-1
11:39 AM Application: xxnet-1
11:39 AM Host: appengine.google.com
11:39 AM Rolling back the …

精简部署 bat 传输全部参数的方法

---

code/default/gae_proxy/server/README.md
code/default/gae_proxy/server/README_en.md

[查看效果](https://github.com/XX-Net/XX-Net/blob/53549d28e3cf1ae1d94f44cb6a2096d0d2a6ac52/code/default/gae_proxy/server/README.md)

更新部署工具的使用说明

---

code/default/gae_proxy/local/web_control.py
code/default/python27/1.0/lib/noarch/simple_http_server.py

默认会缓存，页面会持续刷新浏览器的缓存。
新建一个函数，感觉比附上常量参数更清晰。
问题开始于 https://github.com/XX-net/XX-Net/commit/c9b7d5703428d172cfdcd4f0be9273f1cb06bd26#diff-54e19e48d85da2714de3922cbc0414abL185

no-cache for ajax requests

---

code/default/gae_proxy/local/web_control.py

使用后关闭version.txt

---

code/default/gae_proxy/local/proxy_handler.py

macOS Sierra call socket. gethostbyname_ex got "[Errno 8] nodename nor servname provided, or not known"

Workaround gethostbyname_ex failed on macOS

---

code/default/gae_proxy/local/check_local_network.py

断网时IP会不断丢失
详见：https://github.com/xyuanmu/XX-Mini/issues/107

fix lost ip when disconnecting Internet

---

code/default/launcher/mac_tray.py

修复 #4551
对调这两条命令以后就可以成功修改`mac_helper`的SUID权限

Fix mac_helper permission

---

xx_net.sh

1,mv xx_net.sh to 'root' dir,for no need to change the service link when do update.
2,according code/version.txt to start the specific version xx_net
3,add 'status' command for service

针对xx_net.sh做的修改

---

code/default/python27/1.0/lib/email/mime/application.py
code/default/python27/1.0/lib/email/mime/audio.py
code/default/python27/1.0/lib/email/mime/base.py
code/default/python27/1.0/lib/email/mime/image.py
code/default/python27/1.0/lib/email/mime/message.py
code/default/python27/1.0/lib/email/mime/multipart.py
code/default/python27/1.0/lib/email/mime/nonmultipart.py
code/default/python27/1.0/lib/email/mime/text.py

fix https://github.com/XX-net/XX-Net/issues/5644

修复不能部署appid

---

code/default/gae_proxy/local/check_local_network.py

bugfix report network fail&check #5631

---

launcher/update_from_github.py

Simplify the code a bit by using system separator instead of checking platform and use different separator for different platforms

Simplify the code a bit by using system separator

---

code/default/gae_proxy/local/gae_handler.py
code/default/gae_proxy/server/gae/gae.py
xx_net.sh

在非本目录使用xx_net.sh脚本时，PACKAGE_PATH会取得不正确的值，

修复在非本目录使用xx_net.sh时出错

---

code/default/launcher/start.py

https://github.com/XX-net/XX-Net/issues/6355#issuecomment-326749536

修复3.4.1首次运行启动失败的问题

---

code/default/update_version.txt

fix "get_version_fail" exception which causes xx-net not auto-updating

Update update_version.txt to fix "get_version_fail" exception which causes xx-net not auto-updating

---

code/default/gae_proxy/local/cert_util.py

Currently cert_util generates a 10-year certificate for sites. That's way too long for one certificate (and cause errors like https://github.com/XX-net/XX-Net/issues/6151).
This PR fixes it.

reduce cert validity time

---

code/default/launcher/lang/zh_CN/LC_MESSAGES/messages.po
code/default/launcher/web_ui/config.html

A link to github xxnet release page. Add this link in    system config --> upgrade manegement.

Add link "All versions download page" on web

---

code/default/gae_proxy/web_ui/status.html
code/default/launcher/web_ui/css/style.css

popup notify on web homepage, with 
1.text notify
2.a button that can hopefully send command to python
3.close notify button

add function on web : popup notify

---

code/default/gae_proxy/local/connect_manager.py

Add G2/3 verify

---

code/default/launcher/web_ui/index.html

https://github.com/XX-net/XX-Net-dev/issues/38#issuecomment-336622737

Fix deploy log get

---

code/default/gae_proxy/local/cert_util.py
code/default/launcher/config.py
code/default/launcher/create_shortcut_linux.sh
code/default/launcher/update.py
start

User can use env var or config to prevent XX-Net from modifying system

NO_MESS_SYSTEM support

---

code/default/gae_proxy/local/http1.py
code/default/gae_proxy/local/http2_connection.py
code/default/gae_proxy/local/http_common.py
code/default/gae_proxy/local/http_dispatcher.py
code/default/x_tunnel/local/cloudflare_front/front.py
code/default/x_tunnel/local/cloudflare_front/http1.py
code/default/x_tunnel/local/cloudflare_front/http2_connection.py
code/default/x_tunnel/local/cloudflare_front/http_common.py
code/default/x_tunnel/local/cloudflare_front/http_dispatcher.py
code/default/x_tunnel/local/gae_front.py
code/default/x_tunnel/local/heroku_front/front.py
code/default/x_tunnel/local/heroku_front/http1.py
code/default/x_tunnel/local/heroku_front/http2_connection.py
code/default/x_tunnel/local/heroku_front/http_common.py
code/default/x_tunnel/local/heroku_front/http_dispatcher.py
code/default/x_tunnel/local/proxy_handler.py
code/default/x_tunnel/local/proxy_session.py
code/default/x_tunnel/local/web_control.py
code/default/x_tunnel/web_ui/status.html

https://github.com/XX-net/XX-Net-dev/issues/70
最终效果就是这样：

X-Tunnel debug

---

code/default/gae_proxy/local/check_ip.py
code/default/x_tunnel/local/cloudflare_front/check_ip.py
code/default/x_tunnel/local/heroku_front/check_ip.py

Disconnecting sleep

---

code/default/gae_proxy/local/proxy_handler.py

fix bug: value not found

---

code/default/gae_proxy/local/proxy.pac

use 'PROXY GOAGENT_LISTEN' instead of 'PROXY 127.0.0.1:8087'

update proxy.pac 'PROXY GOAGENT_LISTEN'

---

code/default/gae_proxy/local/cert_util.py
code/default/gae_proxy/local/proxy_handler.py

https://github.com/XX-net/XX-Net/issues/8852#issuecomment-350542494
#8941
#8943
#8946
#8958 
#8962

fix OpenSSL compatibility  and cert bug

---

code/default/launcher/start.py
code/default/launcher/update_from_github.py
code/default/launcher/web_control.py
code/default/launcher/web_ui/config_update.html

option to delete old versions UI

---

code/default/gae_proxy/lang/zh_CN/LC_MESSAGES/messages.po
code/default/gae_proxy/web_ui/advanced.html
code/default/gae_proxy/web_ui/config.html
code/default/gae_proxy/web_ui/deploy.html
code/default/gae_proxy/web_ui/scan_log.html
code/default/gae_proxy/web_ui/status.html
code/default/launcher/lang/zh_CN/LC_MESSAGES/messages.po
code/default/launcher/web_ui/index.html
code/default/smart_router/lang/zh_CN/LC_MESSAGES/messages.po
code/default/smart_router/web_ui/config.html

update web_ui & translation

---

code/default/launcher/web_ui/index.html
code/default/x_tunnel/lang/zh_CN/LC_MESSAGES/messages.po
code/default/x_tunnel/web_ui/menu.yaml
code/default/x_tunnel/web_ui/tls_relay_front_logging.html

- improve '#welcome'
- fix 'tls_relay_front_logging'

fixes & improvements

---

code/default/launcher/gtk_tray.py
code/default/launcher/start.py

Revert "migrate from PyGTK to PyGObject (also GTK2 to GTK3)"

---

code/default/launcher/gtk_tray.py

1. 现在AppIndicator只在Unity、Enlightenment和基于Qt的桌面环境开启，以避免某些基于GTK的桌面环境中AppIndicator造成的托盘图标过大的问题。fix #10067 #10113
2. 给托盘图标添加正确的title “XX-Net”，而不是默认的“setup.py”。
3. “restart gae_proxy” 菜单项变为 “Reset Each Module” （与其他平台保持一致）

GTK托盘功能优化与修正

---

code/default/gae_proxy/local/gae_handler.py
code/default/gae_proxy/local/proxy_handler.py

基于性能和复杂度考虑，没有检查内容，不知道有没有误检。
试了很多次搜索还是没触发 503，懒得试了。。。

try fix google 503

---

code/default/launcher/create_shortcut.js

Pin shortcut to Quick Start Bar and Start Menu.

---

code/default/gae_proxy/local/ipv6_tunnel/enable_ipv6.bat
code/default/gae_proxy/local/ipv6_tunnel/win10.py
code/default/gae_proxy/web_ui/ipv6_tunnel.html

That function is a misunderstanding, It won't work as expected.
More see https://tools.ietf.org/html/rfc3484

Remove IPv6 priority setting (by invalid)

---

code/default/smart_router/local/connect_manager.py
code/default/smart_router/local/pipe_socks.py

Improve pipe socks in smart route
