launcher/1.1.1/update.py
避免遇到【没有文件扩展“.js”的脚本引擎。】错误。
在 `HKEY_CLASSES_ROOT\.js` 的默认值非 `JSFile` 的情况下也能正常运行。
见 `wscript /?`
未添加 //B 忽略错误，以获得更多错误情况（若有）。
建议未来用Python实现（需要研究API）。
=> Explicitly JScript

launcher/1.2.0/systray/traybar.py
原来的代码无效，可能因为原句柄仍有效。不完美（实际进行检测），但有效。
=> Fix the TrayIcon re-create not work properly

launcher/1.4.0/web_ui/config.html, launcher/1.4.0/web_ui/css/style.css
把HTML中的`style`标签合并到CSS中, 尽量不要在HTML中使用`style`标签.
例外: `style="display: none;"` 这是因为JavaScript中的`slideUp()`和`slideDown()`函数的原理是修改style中的这个属性, 写到CSS中就会变得不太直观.
=> Refine the HTML and CSS.

goagent/3.1.49/web_ui/config.html, goagent/3.1.49/web_ui/status.html, launcher/1.4.0/web_ui/config.html, php_proxy/1.0.0/local/web_control.py, php_proxy/1.0.0/web_ui/config.html
1. 当GoAgent或PHP代理状态改变时自动刷新系统设置页面, 目前的策略是当开关触发后, 5秒后刷新页面. 因为我不知道后台的重启什么时候可以完成.(貌似`get_config`)状态不会有变化.
2. Refine HTML in some pages(主要是`GoAgent`的`status`和`config`). Status页面当获取状态失败时, 会自动滚动屏幕到顶部.
3. 去除了PHP代理配置页面中的开关, 同时删除了`web_control.py`的`user_config.php_enable = self.postvars['php_enable'][0]`. 应该没做错吧? 测试了好像没问题.
=> 当GoAgent或PHP代理状态改变时自动刷新系统设置页面

python27/1.0/lib/distutils/version.py
修复 #297 。
在 1.13.0 中，launcher 的 [config.py](https://github.com/XX-net/XX-Net/blob/master/launcher/1.4.0/config.py#L7) 使用了 distutils.version 模块，但在自带的 Python 中没有 distutils，这会导致报错。
=> Add module distutils.version

goagent/3.1.49/local/check_ip.py
=> use HEAD instead of GET in test_server_type

launcher/1.4.0/web_ui/config.html
用户设置手动升级，点击检查更新，如果有新版本，点击后显示升级进度，如果刷新了页面，情况如同【情况2】。
用户设置自动升级，自动升级进行时偶然进入配置页面，显示升级进度。
加班无聊时顺便完成了，暂测没有问题，请核实：D
=> Updated 根据情况展示升级状态 \n Fixed 顺手修复写错的tip调用

launcher/1.4.0/web_ui/index.html
标识符方面，用时间戳或者问题号都有麻烦（需要转换，不直观；无法预测），js也还没有版本号机制，所以干脆用日期吧。
=> Purge site.js cache, fix #385

goagent/3.1.49/local/openssl_wrap.py, goagent/3.1.49/local/proxy_handler.py
因为ssl_sock是由ssl模块或者OpenSSL模块建立的，所以搜索了一下，在适当的位置添加指定的ciphers。
ssl模块创建ssl_sock是由ssl.wrap_socket实现的，直接添加在此函数的参数中，
而OpenSSL模块创建ssl_sock，则灵活（复杂）一点，先创建SSLContext，再用OpenSSL.SSL.Connection函数把SSLContext和socket合并起来。需要在SSLContext的创建过程中，用Context.set_cipher_list（ssl_context.set_cipher_list）函数指定ciphers。
测试结果：
1、可以正确添加gvs ip到good_ip.txt中，在good_ip.txt中显示为gws
2、用python2 start.py命令刚打开时，可以正常工作。但过一会就不断打印“warning no gws ip”警告，并且不能继续访问。好像是这些ip只能完成一次连接就被程序弃用了。具体原因未知。
调试时，把good_ip.txt,bad_ip2.txt删掉，ip_range.txt换成自己找到的gvs ips
=> (have bug,need help)To support gvs ip,add ECDHE... ciphers to ssl_sock generated by ssl module or OpenSSL module

goagent/3.1.49/web_ui/logging.html
模拟一个互斥/线程锁。
因为是500毫秒获取一次，如果当时负载较重（比如浏览器卡住），处理过程超过500毫秒，就会发起两次。那样会导致offset的值冲突，因而判断失误导致日志出现重复。
=> Avoid duplication fetch for logging page

goagent/3.1.49/web_ui/status.html
主要目的是拖拽选中时（尤其是选中字段的一半内容时），不要被无用的刷新影响。其次是减少一些DOM重构消耗。
=> Refine status update process

goagent/3.1.49/local/check_ip.py, goagent/3.1.49/local/connect_control.py, goagent/3.1.49/local/google_ip.py
检测功能，避免在遇到“异常流量”警告后继续扫描。
将扫描线程数调到比如500，持续运行数分钟，就能看到这样的警告。
警告页面参考 https://ipv4.google.com/sorry/IndexRedirect
备注：如果检测机制改成只获取和检查证书但不获取资源，频率高也不会触发这样的警告。
=> Implement Scan Blocked detect

goagent/3.1.49/local/google_ip.py, goagent/3.1.49/local/logging.py, goagent/3.1.49/local/web_control.py, goagent/3.1.49/web_ui/logging.html, goagent/3.1.49/web_ui/scan_ip.html, launcher/1.4.0/web_control.py, php_proxy/1.0.0/local/web_control.py
* 主要
* 改善添加性能，一次获取只进行一次添加和一次滚动操作（DOM）。
* 自动移除旧日志语句已注释，参数和方式未考虑好。持续添加会导致内存持续增长。但如果超出指定值后每次获取（500ms）都修剪似乎也增加了负担，虽然我这里看上去不卡。
* 获取时，如果没有新日志，可直接返回0字节响应（200 OK），减少传输和判断消耗。
* 尝试改善稳定性。有时会突然持续添加重复的日志，症状为返回的JSON中第一项不是最低项（最低项跑到了最后一项）导致检查失误。原因不明，遇到过多次，希望排序能够解决。
* 很小的排序耗时不必输出，跳过小于30ms（大约6000 ip）的输出。
* 扫描日志目前仅在载入或手动刷新时更新，所以每次更新时跳转到最底部就可以了。
* 次要
* 配平引号。
* get_last_lines 用途不明，如果已废弃，请考虑删除。
=> Refine logs function

php_proxy/local/proxy.py
* 修复当python升级到2.7.10时，php proxy version的显示不正确的问题
=> Fix phpproxy version

gae_proxy/local/openssl_wrap.py
from twitter user "himanzero"
https://twitter.com/himanzero/status/645231724318748672
```
Himan Zero ‏@himanzero Sep 19
在FreeNAS里装上XX-Net，出错，调试发现FreeBSD的OpenSSL不支持TLSv1_2。于是在openssl_wrap.py相应位置加了一行if sys.platform == "freebsd9": ssl_version = "TLSv1"，搞定。#人生经验+1
```
闲逛twitter时发现 :laughing:
=> freenas openssl support fix

gae_proxy/local/simple_http_server.py, launcher/web_control.py
=> Fix issue https://github.com/XX-net/XX-Net/issues/1422

launcher/gtk_tray.py
Make sure python-appindicator had been installed.
If not, run `sudo apt-get install python-appindicator`
Signed-off-by: jitao <jt6562@gmail.com>
=> Add Ubuntu system trayicon using libappindicator.

README.md
As indicated by the title. Strictly speaking, ComodoDragonPortable is not integrated with XX-Net. The original description is misleading. Chinese description will be added on the project page soon.
=> Describe ComodoDragonPortable accurately in README

README.md
A small improvement: "A Reborn of Goagent" should be "A Reborn Goagent".
=> Correct an English grammatic error in README.md

start.command
我用fish作为默认shell，它与bash语法不兼容，执行start.command时会出错。
在头部声明bash可解决此问题。
=> [OS X] Specify bash in start.command

gae_proxy/local/proxy_handler.py, gae_proxy/web_ui/status.html
1. mobile browser can browse server correctly
2. 'enable_remote_web_control ' must be set 'on' in config page
=> Mobile browser can browse webcontrol and download ca.cert correctly

gae_proxy/local/proxy_handler.py
~~Add HTTP message body.~~Refer to
http://tools.ietf.org/html/rfc7230#section-3.3.3
to fix issue:
https://groups.google.com/forum/#!topic/xx-net/baJlca97RJU
#2183  #2134
=> fix google.com on http in firefox

gae_proxy/lang/de_DE/LC_MESSAGES/messages.po, gae_proxy/lang/es_VE/LC_MESSAGES/messages.po, gae_proxy/lang/fa_IR/LC_MESSAGES/messages.po, gae_proxy/lang/ja_JP/LC_MESSAGES/messages.po, gae_proxy/lang/zh_CN/LC_MESSAGES/messages.po, gae_proxy/local/web_control.py, gae_proxy/web_ui/config.html, gae_proxy/web_ui/status.html
思路：
* 语义化数字含义。OS Detail和UA也有冒号，所以重叠的结构应该没问题。
* 对于外国用户，CERNet这种描述不必要。为了避免误解为全自动检测（实际也是，但会有提示出现），没有用'(If available)'。不确定'Enabled IPv6'是否更适合。
* 加'...'避免误解为直接发送，虽然也能从链接看出来，但不保险也不贴合用户。其实正规写法是GitHub，但Github应该也行，全小写则比较不规范。i18n模板内容。
问题：
* po文件是如何更新的，目前有一个翻译平台或提取工具吗。用poedit提取（生成po）失败，默认它好像不支持html文件。
* 有一个'You may want to'字符串在po文件中不完整，需要纠正和翻译。
=> Improve messages

gae_proxy/local/web_control.py
在 https://github.com/XX-net/XX-Net/commit/7e2ef7b70336962c5dfc38544c300180c29ffcc9 开始失效。
新的代码会允许代码嵌入网页，可能带来恶意代码问题。不过直接在子目录的文件插入代码是一样的，并且更隐蔽，所以好像不是问题。
未测试version.txt的自动更新效果。
=> Fix get_version_fail in xxnet_version

gae_proxy/web_ui/check_ip.html
非检查状态也应该刷新所有和可用IP，方便查看。这个界面比状态页面的信息更简洁。
=> Always refresh check_ip interface

gae_proxy/lang/fa_IR/LC_MESSAGES/messages.po, gae_proxy/lang/zh_CN/LC_MESSAGES/messages.po, gae_proxy/web_ui/deploy.html, gae_proxy/web_ui/status.html, launcher/lang/zh_CN/LC_MESSAGES/messages.po, launcher/web_control.py, launcher/web_ui/css/style.css, launcher/web_ui/index.html
* 添加一个标识符，避免不知不觉/忘记启用了远程连接造成安全风险。
* 其实若支持HTTP基本验证、SSL通讯等更好，但均非主要功能，开发资源紧张先不管吧。
* 有考虑用红字，但目前白字也很醒目。那个规则似乎无作用且没有被使用，清理。
* 英文版中描述较长，但也足够放，缩写或者图标感觉会降低作用。
* 已测试无字符串的语言会自动采用英语。
* `{{ _( `中必须用双引号，不然程序执行时陷入死循环，控制台在不断输出网页代码。
* 临时解决`#`字符被脚本替换截断的问题，#2401 曾提到。
* 未来可以弄一个翻译平台，比如用 http://docs.transifex.com/client/setup/
* https://hosted.weblate.org 界面也不错，申请需人工审核 (https://weblate.org/zh-hans/hosting/) 不知道遇到了什么困难。
=> Improve 160328,  add a remote-connection-identifier, etc.

gae_proxy/local/cert_util.py
如果不try，在新data目录时，如果用户拒绝UAC（导入新证书），代理和网页界面端口不会开始服务，只有扫描IP的组件在运行。应该允许拒绝UAC导入，然后手动操作（下载证书和处理，或者只是看界面和扫描IP等）。未将整体纳入，未纳入import_linux_firefox_ca等同类函数，因为未考量其他执行失败的情况。
=> Allow import_windows_ca failed, user may reject to UAC

gae_proxy/web_ui/config.html, gae_proxy/web_ui/scan_setting.html, gae_proxy/web_ui/status.html, launcher/web_ui/config.html, php_proxy/web_ui/config.html
This reverts commit e83a767c3329de63477dda1e31a6eb80bab2edc0.
之前的想法错了，bootstrapSwitch会触发change事件。
[据说](https://github.com/nostalgiaz/bootstrap-switch/issues/123)第三个参数设true可以跳过，但change事件经测不能跳过。试了`.on('switchChange.bootstrapSwitch'`等事件，均无法正常触发。
最后发现当前库的版本可以用`.bootstrapSwitch('setState'`事件，并且似乎始终会跳过bootstrapSwitch事件。但多处重构后还是有很多莫名失效，调试许久无果。还是恢复原来的办法吧。
=> Revert "use bootstrapSwitch to switch"

gae_proxy/local/gae_handler.py
urllib is used in [line 455](https://github.com/XX-net/XX-Net/blob/master/gae_proxy/local/gae_handler.py#L455), but not imported
=> Add `import urllib`

gae_proxy/local/check_ip.py
python3 版本的 check_ip 中重置 network_stat、last_check_time、continue_fail_count 的功能，在断网的情况下会不断更新使 _simple_check_worker 不能被激活，从而导致大量IP失效，只不过失效的时候不会更新 good_ip.txt，但是重新联网依然会更新到 good_ip.txt ，此现象只在python3版出现，python2不会。
=> fix lost ip quickly when network not available

start.sh, xx_net.sh
修复python命令默认为启动Python3时xx_net.sh第60行处报错；
并修改为通过Python -V来检测Python版本，因为部分情况下通过hash不一定能正常判断Python版本
=> 更改Python版本检测方法&修正xx_net.sh中的一个小错误

start.command
Resolves #2622 where python installed from Anaconda overrides OS X built-in python.
**Do not merge** before fixing #2206 (Autoupdate drops execute permission of start.command)
=> [WIP] Specify system python in start.command

start.bat
修复存放文件夹带空格/特殊字符时，不能启动的问题
问题如下：
D:\Program Files (x86)\XX-Net>start.bat
D:\Program Files (x86)\XX-Net>SET PYTHONPATH=
D:\Program Files (x86)\XX-Net>D:\Program Files (x86)\XX-Net\start.vbs console
'D:\Program' is not recognized as an internal or external command,
operable program or batch file.
=> 修复文件夹带空格时不能运行的问题

code/default/launcher/post_update.py, code/default/launcher/start.py, code/default/launcher/update_from_github.py, launcher/start.py
加入更新后自动迁移功能，在启动时检测上次运行的版本，如果小于目前版本则触发迁移。
迁移逻辑在`post_update.py`中，目前会给`xxnet`加执行权限，删除无用文件和目录，并重新配置开机自动启动（解决Windows下自启老版本的问题）。
经简单测试能从2.3.0和3.0.4自动升级至此版本。如果进一步测试能通过，可以把下载页面移回主页。
本PR依赖于#2944。
=> 修复2.X自动更新（依赖 #2944）

code/default/launcher/post_update.py, launcher/DO_NOT_PUT_ANYTHING_HERE
#2987 是此问题的彻底解决方案，但如果不希望顶层添加文件，这个方法也能保证每次更新自动删除launcher文件夹。
这种方法的坏处是如果以后增减顶层文件而不修改`post_update.py`，则从3.0.4或更早版本升级上来时会出问题。
=> 更新时自动删除launcher文件夹（#2987 的备选方案）

code/default/xx_net.sh
the shell script for backend:
- start func: the end `fi`
- stop func: grep string and the `truei` typo
=> fix(xx-net.sh): some bugs cause by previous commit

start
解决了评论中提到的问题
https://github.com/XX-net/XX-Net/issues/3040#issuecomment-215039486
目前测试的操作系统有:
Ubuntu 16.04, 10.04; Cent OS 7
Debian晚些时候我会测试，应该和Ubuntu是一样的。
Mac上的安装可能需要借助于`brew`。
其他Linux发行版我晚些时候再完善，也请小伙伴们一起帮忙完善。
=> Check whether python-openssl is installed when startup.

code/default/launcher/autorun.py, code/default/launcher/start.py, start
自动启动时不能忽略hungup信号
修复#3187 #3163
=> Fix autorun on Mac

start
系统自带python使用openssl 0.9.8，不支持http2。
homebrew中python依赖openssl，安装时会自动安装最新版openssl。
最后使用pip安装pyopenssl。
=> Python warning on Mac

start
Add script for openSUSE
only auto-install in interactive shell
把 openSUSE 的检测改到最前面是因为 openSUSE 自带了 apt-get 和 aptitude 两个 perl 脚本来转换并兼容部分 deb 系的命令……这样如果先检测 apt-get 的话可能有问题（不过我改了检测 pyOpenSSL 是否安装的方法之后目前顺序貌似不重要）。
=> Improve installation script for linux

start
在start脚本启动时，创建了一个start.desktop文件，将这个文件拖入启动栏，就可以通过点击启动栏图标启动软件。
适用于ubuntu系统。
=> Add:create a startup file for ubuntu

code/default/gae_proxy/server/uploader.bat, code/default/gae_proxy/server/uploader.py
因为现在部署页面已经没有了密码设置，而且 uploader.py 里也没法设置密码，现在的代码会导致根本无法设置 RC4 密码。
uploader.py 会在部署之前强行将 gae.py 与 wsgi.py 的密码清空，而 uploader.py 自己也不支持设置密码，所以现在除非修改 uploader.py 否则根本没办法设置 RC4 密码。
因此这里把修改 RC4 密码的代码直接删掉了。
=> 部署服务端的时候不再修改 RC4 密码

code/default/gae_proxy/local/google_ip.py
遇到过多次#3408的问题。这大概能解决。参考了 https://github.com/XX-net/XX-Net/blob/6f054189250462317854d554ace1987ebb833053/code/default/gae_proxy/local/scan_ip_log.py#L52
=> flush when saving good_ip.txt, fix #3408

code/default/gae_proxy/local/check_local_network.py, code/default/gae_proxy/local/google_ip.py, code/default/gae_proxy/web_ui/status.html, code/default/launcher/post_update.py
"scan_ip_worker exit" 在减少线程数时会大量输出，用途不明。
削除行尾换行造成的一个空格。
避免上次运行版本格式错误时无法启动。
=> 2016.06.05 Small fixes

code/default/gae_proxy/local/config.py, code/default/gae_proxy/local/proxy_handler.py
In some situations, you may only want specified hosts accross the gae proxy but others not.
For example, you are running your docker cluster but some registries required can not be accessed normally. In this case, you can force all your docker daemon network data flowing through such proxies.
In other words, you can not decide which registry will be accessed through real proxy and which not. The only thing you can do is accessing all these registries through your gae proxy or not.
If you have this patch, you can configure these hosts and make them through your proxy but rest not. As following configuration in your `config.ini`:
[proxy]
hosts = gcr.io|google.com|googleapis.com
From this point, only these hosts will through your gae proxy but others not.
How about if I do not specified this …
=> Support reverse rules for proxy by specifying `proxy.hosts`

code/default/gae_proxy/local/proxy.ini
Simple fix for the issue described in following issues:
https://github.com/XX-net/XX-Net/issues/4731
https://github.com/XX-net/XX-Net/issues/4712
So that to avoid users to modify the file by hand.
=> add param 'hosts =' to avoid error on start

code/default/gae_proxy/local/check_local_network.py
之前的两个检测IPv6的网址无法正常打开，遂替换为：
- 六维空间: `bt.neu6.edu.cn`
- DragonLab实验室: `www.cernet2.net`
替换的网址满足条件: DNS解析后仅返回IPv6地址.
=> Fix issue #3766.

start
这个问题我已经忍了好久了, 主要的修改有2个:
1. Fix ArchLinux下的OpenSSL是否安装的判断, 之前的脚本会默认使用Python 3.
2. 删除了Interactive Shell的判断, 感觉之前的那个判断会影响OpenSSL正常的安装.
我启动XX-Net的方式是`./start`, 每次都不会执行安装脚本. 都提示我`Please install pyOpenSSL`.
=> Fix installtion script for OpenSSL in Linux.

code/default/gae_proxy/local/cert_util.py
Both Firefox and Chrome now require "subjectAltName" to exist instead
of just "commonName". Otherwise they report SSL_ERROR_BAD_CERT_DOMAIN
and net::ERR_CERT_COMMON_NAME_INVALID, respectively.
This fixes #5044, fixes #5093, fixes #5106, fixes #5110, and
fixes #5116.
=> gae_proxy: cert_util: add subjectAltName extension

code/default/launcher/update_from_github.py
files in '/sdcard' are not allowed to chmod
=> fix update fail for Android

code/default/launcher/update.py
In Python 3, `reduce()` was moved to functools.
https://docs.python.org/3/library/functools.html#functools.reduce
=> If Python 3 then from functools import reduce

code/default/launcher/web_control.py
A lambda (or a normal function) can not take an explicit tuple as a parameter in Python 3.  Change the lambda to instead take a two tuple (k_and_v) as a single parameter which contains both a key and a value and then use only the value (k_and_v[1]) in the sorted() function.
This is the last issue blocking #6061
=> Python 3 lambda cannot take explicit tuple param

code/default/gae_proxy/server/gae/gae.py
This will cause Fatal problem in GAE server !!! Result in GAE_Exception 605 'status:500'
Google Log Report:
11:33:20.864
(/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263)
Traceback (most recent call last):
File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
handler, path, err = LoadObject(self._handler)
File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
obj = …
=> Emergency Fix: SyntaxError: invalid syntax - 服务器端 Python 语法 BUG 紧急修复！

code/default/gae_proxy/web_ui/status.html, code/default/launcher/lang/zh_CN/LC_MESSAGES/messages.po, code/default/launcher/update.py, code/default/launcher/update_from_github.py, code/default/launcher/web_control.py, code/default/launcher/web_ui/config.html, code/default/launcher/web_ui/css/style.css, code/default/launcher/web_ui/index.html
需测试，有条件感兴趣的请帮忙。
为方便测试，可下载 [XX-Net-update-tip.zip](https://github.com/XX-net/XX-Net/files/1374175/XX-Net-update-tip.zip) 覆盖到 XX-Net 目录，会保持更新。
以下是设计目标：
>原来的升级设置选项：
>1. 不更新
>1. 自动升级到稳定版
>1. 自动升级到测试版
>
>修改为：
>1. 有稳定的新版时，通知（默认设置）
>1. 自动升级到稳定版
>1. 有测试的新版时，通知
>1. 自动升级到测试版
>1. 不更新
>
>通知后，有 4 个选择：
>1. 同意，立即更新
>1. 不再提示这个版本（需要记录下来本次提示的版本，下次检查到不提醒）
>1. 下次再提醒（什么也不做，下次启动会再提醒） #此处修改，非下次启动，改为 24 小时后
>1. 关闭，可以当作“下次再提醒我” 处理
增加：
显示下载进度，与之前的手动升级系统兼容。
**重要改变：**
子页面要使用 `$(document).ready` 时，不能直接调用，需要将函数放入主页面定义的 `documentReadyToRun` 数组，主页面会自动调用。
=> Add update notify

code/default/gae_proxy/local/gae_handler.py
Except stack:Traceback (most recent call last): File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/smart_router/local/smart_route.py", line 297, in try_loop do_gae(sock, host, port, client_address, left_buf) File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/smart_router/local/smart_route.py", line 266, in do_gae req.do_METHOD() File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/gae_proxy/local/proxy_handler.py", line 223, in do_METHOD return self.do_AGENT() File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/gae_proxy/local/proxy_handler.py", line 271, in do_AGENT gae_handler.handler(self.command, self.path, request_headers, payload, self.wfile) File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/gae_proxy/ …
=> fix content_range error

code/default/python27/1.0/lib/noarch/front_base/http2_connection.py
Feb 23 12:38:12.885 [cloudflare_front][ERROR] Except stack:Traceback (most recent call last):
File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.10.4/python27/1.0/lib/noarch/front_base/http2_connection.py", line 205, in recv_loop
self._consume_single_frame()
File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.10.4/python27/1.0/lib/noarch/front_base/http2_connection.py", line 305, in _consume_single_frame
frame, length = Frame.parse_frame_header(header)
File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.10.4/python27/1.0/lib/noarch/hyper/packages/hyperframe/frame.py", line 75, in parse_frame_header
fields = struct.unpack("!HBBBL", header)
error: unpack requires a string argument of length 9
Feb 23 11:42:30.462 [cloudflare_front][ERROR] Except …
=> fix http2 recv fail

code/default/launcher/gtk_tray.py, code/default/launcher/start.py
之前XX-Net在Linux桌面所依赖的PyGTK很多年以前就不再维护了，其官网也建议使用PyGObject来取代它。
于是我创建了这个PR，从PyGTK迁移到了PyGObject，顺带地也将图形库的依赖从GTK2升级为GTK3。
当然，XX-Net的一些依赖也会改变（从pygtk, python-appindicator, python-notify简化为python-gobject, libappindicator和libnotify），如果PR被采纳，我会跟进更新Wiki页面。
最后，还修正了一个typo :-)
=> migrate from PyGTK to PyGObject (also GTK2 to GTK3)

code/default/launcher/gtk_tray.py, code/default/launcher/start.py
https://github.com/XX-net/XX-Net/pull/9990 的升级版，此次改为对pygtk和python2-gobject双兼容，如果系统装有python2-gobject，则自动使用，否则使用pygtk（跟此前行为完全一致）。
=> add PyGObject as an alternative GTK backend dependency to PyGTK

code/default/launcher/gtk_tray.py, code/default/launcher/start.py
#9994 修改中，基于PyGObject的实现在某些系统上会导致设置页面打不开，原因未知，因此改回默认使用PyGTK。
fix #10046 fix #10080 fix #10112 fix #10113 fix #10193
=> gtk_tray 优先使用 pygtk

start.vbs
[FIX] double click "start.vbs" doesn't work if environments conflict
=> [FIX] double click "start.vbs" doesn't work if environments conflict

code/default/gae_proxy/local/config.py
警告：
此补丁去除了对 GAE IP 的 commonname 检查，publickey 检查仍然工作。
请保持 pyOpenSSL 版本大于 16.0.0，不要使用旧版本！否则可能被中间人攻击。
=> disable gae commonname check

code/default/gae_proxy/server/uploader.py, start
missing pyopenssl when exists multiple python env&&add skip proxy command option
pyenv环境下缺pyopenssl导致启动失败
上传部署appid通过参数控制不使用代理
=> missing pyopenssl when exists multiple python env

code/default/lib/noarch/sortedcontainers/sortedlistwithkey.py
% `flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics`
```
./code/default/lib/noarch/sortedcontainers/sortedlistwithkey.py:1:1:
E999 ValueError: source code string cannot contain null bytes
^
1     E999 ValueError: source code string cannot contain null bytes
1
```
=> Remove the last char (0x00) in the file

.github/workflows/notify_aur_upgrade.yml
I am a maintainer of [aur/xx-net repo](https://aur.archlinux.org/packages/xx-net). 
Now, I am using github workflow to realize automatic upgrade.
Send a workflow_dispatch request to a workflow of lisuke/PKGBUILD repo, notify that the workflow aur/xx-net can start upgrading.
=> add workflow:  notify_aur_upgrade
